# Generated by Django 4.0.6 on 2022-07-14 01:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0005_alter_kelas_kode_alter_kelas_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Golongan')),
                ('ket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterangan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JabatanFungsional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Jabatan')),
                ('ket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterangan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JabatanStruktural',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Jabatan')),
                ('ket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterangan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JenisPTK',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama PTK')),
                ('ket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterangan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPegawai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Status')),
                ('ket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterangan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('nip', models.CharField(max_length=100, verbose_name='NIP / NIY')),
                ('kode', models.CharField(max_length=100, verbose_name='Kode Pegawai')),
                ('tempat_lahir', models.CharField(max_length=100, verbose_name='Templat Lahir')),
                ('tgl_lahir', models.DateTimeField(verbose_name='Tanggal Lahir')),
                ('jns_kelamin', models.CharField(choices=[('laki_laki', 'Laki - laki'), ('perempuan', 'Perempuan')], max_length=20, verbose_name='Jenis Kelamin')),
                ('pendidikan', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma_smk', 'SMA/SMK'), ('d3', 'D3'), ('s1', 'S1'), ('s2', 'S2')], max_length=20, verbose_name='Pendidikan Terakhir')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat (KTP)')),
                ('domisili', models.TextField(blank=True, null=True, verbose_name='Alamat (Domisili)')),
                ('no_sk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nomor SK')),
                ('tmt_awal', models.CharField(blank=True, max_length=150, null=True, verbose_name='TMT Awal')),
                ('tgl_masuk', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Masuk')),
                ('tempat_tugas', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tempat Tugas')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telp_wa', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telp / WA')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto')),
                ('golongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.golongan')),
                ('jabatan_fungsional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.jabatanfungsional')),
                ('jabatan_struktural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.jabatanstruktural')),
                ('jenis_ptk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.jenisptk')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.statuspegawai')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
