# Generated by Django 4.0.6 on 2022-07-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='tgl_lahir',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
    ]
