# Generated by Django 4.0.6 on 2022-07-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_alter_pegawai_tgl_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='tgl_masuk',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Masuk'),
        ),
    ]
