# Generated by Django 4.0.6 on 2023-08-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_alter_pegawai_tgl_masuk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golongan',
            options={'verbose_name': 'Golongan', 'verbose_name_plural': 'Golongan'},
        ),
        migrations.AlterModelOptions(
            name='jabatanfungsional',
            options={'verbose_name': 'Jabatan Fungsional', 'verbose_name_plural': 'Jabatan Fungsional'},
        ),
        migrations.AlterModelOptions(
            name='jabatanstruktural',
            options={'verbose_name': 'Jabatan Struktural', 'verbose_name_plural': 'Jabatan Struktural'},
        ),
        migrations.AlterModelOptions(
            name='jenisptk',
            options={'verbose_name': 'Jenis PTK', 'verbose_name_plural': 'Jenis PTK'},
        ),
        migrations.AlterModelOptions(
            name='pegawai',
            options={'verbose_name': 'Pegawai', 'verbose_name_plural': 'Pegawai'},
        ),
        migrations.AlterModelOptions(
            name='statuspegawai',
            options={'verbose_name': 'Status Pegawai', 'verbose_name_plural': 'Status Pegawai'},
        ),
    ]
