# Generated by Django 4.0.6 on 2023-12-14 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0005_alter_pegawai_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clockin', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Masuk')),
                ('clockout', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Keluar')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('sakit', 'Sakit'), ('ijin', 'Ijin'), ('cuti', 'Cuti'), ('absen', 'Absen')], max_length=10, verbose_name='Status')),
                ('ket', models.TextField(blank=True, help_text='Keterangan atau link ref dokumen', null=True, verbose_name='Keterangan')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
