# Generated by Django 4.0.6 on 2022-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='npns',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NPNS'),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='nss',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NSS'),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='telp_wa',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telp / WA'),
        ),
    ]
