# Generated by Django 4.0.6 on 2022-07-14 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_alter_sekolah_email_alter_sekolah_npns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gedung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Gedung')),
                ('kode', models.CharField(max_length=100, verbose_name='Kode Gedung')),
                ('jml_lantai', models.PositiveSmallIntegerField(default=1, verbose_name='Jumlah Lantai')),
                ('panjang', models.FloatField(blank=True, help_text='satuan dalam meter (m)', null=True, verbose_name='Panjang Gedung')),
                ('lebar', models.FloatField(blank=True, help_text='satuan dalam meter (m)', null=True, verbose_name='Lebar Gedung')),
                ('tinggi', models.FloatField(blank=True, help_text='satuan dalam meter (m)', null=True, verbose_name='Tinggi Gedung')),
                ('aktif', models.BooleanField(default=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Ruangan')),
                ('kode', models.CharField(max_length=100, verbose_name='Kode Ruangan')),
                ('kapasitas_belajar', models.PositiveSmallIntegerField(default=0, verbose_name='Kapasitas Belajar')),
                ('kapasitas_ujian', models.PositiveSmallIntegerField(default=0, verbose_name='Kapasitas Ujian')),
                ('gedung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.gedung')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
