# Generated by Django 4.0.6 on 2022-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_jurusan_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='kode',
            field=models.CharField(max_length=100, verbose_name='Kode Kelas'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama',
            field=models.CharField(max_length=150, verbose_name='Nama Kelas'),
        ),
    ]
