# Generated by Django 4.0.6 on 2023-08-03 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_alter_kelas_kode_alter_kelas_nama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gedung',
            options={'verbose_name': 'Gedung', 'verbose_name_plural': 'Gedung'},
        ),
        migrations.AlterModelOptions(
            name='jurusan',
            options={'verbose_name': 'Jurusan', 'verbose_name_plural': 'Jurusan'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='ruangan',
            options={'verbose_name': 'Ruangan', 'verbose_name_plural': 'Ruangan'},
        ),
        migrations.AlterModelOptions(
            name='sekolah',
            options={'verbose_name': 'Sekolah', 'verbose_name_plural': 'Sekolah'},
        ),
    ]
