# Generated by Django 4.0.6 on 2023-08-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_alter_gedung_options_alter_jurusan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedung',
            name='kode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kode Gedung'),
        ),
        migrations.AlterField(
            model_name='jurusan',
            name='kode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kode Jurusan'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='kode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kode Kelas'),
        ),
        migrations.AlterField(
            model_name='ruangan',
            name='kode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kode Ruangan'),
        ),
    ]
