# Generated by Django 4.0.6 on 2023-08-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_alter_gedung_kode_alter_jurusan_kode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.jurusan'),
        ),
    ]
