# Generated by Django 4.0.6 on 2023-08-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0008_alter_kelas_jurusan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='ruangan',
        ),
        migrations.AddField(
            model_name='kelas',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.sekolah'),
        ),
    ]
