# Generated by Django 4.0.6 on 2023-09-05 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_remove_kelas_ruangan_kelas_sekolah'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArsipSiswaKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ket', models.TextField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
