# Generated by Django 4.0.6 on 2023-09-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0011_alter_jadwal_options'),
        ('siswa', '0002_siswakelas_arsipsiswakelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsipsiswakelas',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.tahunakademik'),
        ),
        migrations.AddField(
            model_name='siswakelas',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akademik.tahunakademik'),
        ),
        migrations.AlterField(
            model_name='arsipsiswakelas',
            name='ket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
