# Generated by Django 4.0.6 on 2023-12-22 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0011_alter_jadwal_options'),
        ('siswa', '0003_arsipsiswakelas_tahun_ajaran_siswakelas_tahun_ajaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresensiSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('absen', 'Absen'), ('ijin', 'Ijin'), ('sakit', 'Sakit')], default='absen', max_length=6)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.jadwal')),
                ('siswa_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswakelas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
