# Generated by Django 4.0.6 on 2024-01-03 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akademik', '0011_alter_jadwal_options'),
        ('siswa', '0004_presensisiswa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsipsiswakelas',
            options={'verbose_name': 'Arsip Siswa Kelas', 'verbose_name_plural': 'Arsip Siswa kelas'},
        ),
        migrations.AlterModelOptions(
            name='presensisiswa',
            options={'verbose_name': 'Presensi Siswa', 'verbose_name_plural': 'Presensi Siswa'},
        ),
        migrations.AlterModelOptions(
            name='siswakelas',
            options={'verbose_name': 'Siswa Kelas', 'verbose_name_plural': 'Siswa Kelas'},
        ),
        migrations.CreateModel(
            name='PresensiSiswaHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ket', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.jadwal')),
                ('presensi_siswa', models.ManyToManyField(to='siswa.presensisiswa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presensi Siswa Harian',
                'verbose_name_plural': 'Presensi Siswa Harian',
            },
        ),
    ]
