# Generated by Django 4.0.6 on 2023-08-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_remove_matapelajaran_guru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matapelajaran',
            old_name='khusu',
            new_name='khusus',
        ),
        migrations.RemoveField(
            model_name='matapelajaran',
            name='sekolah',
        ),
    ]
