# Generated by Django 4.0.6 on 2023-08-07 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0005_alter_pegawai_kode'),
        ('sekolah', '0007_alter_gedung_kode_alter_jurusan_kode_and_more'),
        ('akademik', '0004_alter_matapelajaran_kode_alter_tahunakademik_kode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matapelajaran',
            name='jurusan',
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('salasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=15)),
                ('jam_mulai', models.TimeField()),
                ('jam_akhir', models.TimeField()),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.pegawai')),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.jurusan')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matapelajaran')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
