# Generated by Django 4.0.6 on 2023-08-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_remove_matapelajaran_jurusan_jadwal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'verbose_name': 'Jadwal', 'verbose_name_plural': 'Jadwal'},
        ),
    ]
