# Generated by Django 4.0.6 on 2023-08-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_alter_jadwal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='khusus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kompetensi Khusus'),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='umum',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kompetensi Umum'),
        ),
    ]
