# Generated by Django 4.0.6 on 2023-08-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0007_alter_matapelajaran_khusus_alter_matapelajaran_umum'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.tahunakademik'),
        ),
    ]
