# Generated by Django 4.0.6 on 2023-08-09 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0008_matapelajaran_tahun_ajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matapelajaran',
            name='tahun_ajaran',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademik.tahunakademik'),
        ),
    ]
