# Generated by Django 4.0.6 on 2023-08-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_remove_kelas_ruangan_kelas_sekolah'),
        ('akademik', '0009_remove_matapelajaran_tahun_ajaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='ruangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.ruangan'),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='sekolah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.sekolah'),
        ),
    ]
