# Generated by Django 4.0.6 on 2023-08-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0010_jadwal_ruangan_jadwal_sekolah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'ordering': ('-updated',), 'verbose_name': 'Jadwal', 'verbose_name_plural': 'Jadwal'},
        ),
    ]
